config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  resources :users, only: [:new, :create]
  # resources :categories, only: [:index]
  namespace :admin do
    resources :categories, only: [:index, :new, :create, :destroy] #:show
  end
  namespace :user do
    resources :categories, only: [:index] #:show
  end

  resources :ideas
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :ideas
  validates :category, uniqueness: true
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  validates :user_id, presence: true
  validates :category_id, presence: true

  has_many :image_ideas
  has_many :images, through: :image_ideas
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_many :image_ideas
  has_many :ideas, through: :image_ideas
  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :ideas
  validates :username, uniqueness: true, presence: true
  validates :password, presence: true
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_authorization

  def require_authorization
    if !current_user.nil?
      if current_user.admin?
        true
      end
    else
      redirect_to login_path
    end
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  def index
    @categories = Category.all
  end

  def new
  end

  def create
    Category.create(category: params[:category][:category])
    redirect_to admin_categories_path
  end

  def destroy
    Category.find(params[:id]).delete
    redirect_to admin_categories_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :current_user?

  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_user?
    false
    if current_user
      true
    end
  end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :current_user?

  def destroy
    Idea.find(params[:id]).delete
    redirect_to ideas_path
  end

  def index
    @ideas = Idea.where(user_id: current_user.id)
  end

  def new
    @categories = Category.all
  end

  def create
    Category.find(category_id).ideas << Idea.create(idea: user_idea,
                                              user_id: current_user.id)
    redirect_to ideas_path
  end

  def edit
    @idea = Idea.find(params[:id])
    @id = params[:id]
    @categories = Category.all
  end

  def update
    Idea.find(params[:id]).update(idea: params[:idea][:idea],
                                  category_id: params[:idea][:category_id])
    redirect_to ideas_path
  end

  private

  def category_id
    params[:idea][:category_id]
  end

  def user_idea
    params[:idea][:idea]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      user_path
    else
      flash.now[:error] = "Username or Password is Incorrect."
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to login_path
  end

  private

  def user_path
    if @user.admin?
      redirect_to admin_categories_path
    else
      redirect_to user_categories_path
    end
  end

end

app/controllers/user/base_controller.rb
class User::BaseController < ApplicationController
  before_action :require_authorization

  def require_authorization
    if current_user
      true
    else
      redirect_to login_path
    end
  end
end

app/controllers/user/categories_controller.rb
class User::CategoriesController < User::BaseController
  def index
    @categories = Category.all
  end
end

app/controllers/users/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_authorization

  def require_authorization
    if current_user.admin?
      true
    else
      redirect_to login_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:status] = "Account Successfully Created"
      redirect_to login_path
    elsif params_missing?
      flash.now[:error] = "Please Complete Required Fields"
      render :new
    else
      flash.now[:error] = "Username is Invalid"
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

  def params_missing?
    false
    if params[:user][:username] == "" || params[:user][:password] == ""
      true
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/categories/index.html.erb
<%= link_to "Logout", logout_path, method: :delete %>
<%= link_to "Create New Category", new_admin_category_path %>
<%= link_to "Idea Index", ideas_path %>

<h1>Available Categories</h1>

<table class="categories">
  <tr>
    <th>Category Name</th>
    <th>Remove Category</th>
  </tr>

  <% @categories.each do |c| %>
    <tr>
      <td><%= c.category %></td>
      <td><%= link_to "Delete Category", admin_category_path(c.id), method:
      :delete, data: {confirm: "You Sure?"} %></td>
    </tr>
  <% end %>
</table>

app/views/admin/categories/new.html.erb
<%= form_for(:category, url: "/admin/categories") do |f| %>
  <%= f.label :category %>
  <%= f.text_field :category %><br/>

  <%= f.submit "Create Category" %>
<% end %>

app/views/ideas/edit.html.erb
<%= link_to "<< Categories Index", admin_categories_path %>
<%= form_for(@idea, url: "/ideas/#{@id}", method: :put) do |f| %>
  <%= f.label :idea %>
  <%= f.text_field :idea %><br/>

  <%= f.label :category %>
  <%= f.collection_select :category_id, @categories, :id, :category %>

  <%= f.submit "Update Idea" %>
<% end %>

app/views/ideas/index.html.erb
<%= link_to "Logout", logout_path, method: :delete %>

<h1>Available Ideas</h1>

<table class="categories">
  <tr>
    <th>Category Name</th>
    <th>Idea Name</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>

  <% @ideas.each do |i| %>
    <tr>
      <td><%= Category.find(i.category_id).category %></td>
      <td><%= i.idea %></td>
      <td><%= link_to "Edit", edit_idea_path(i.id) %></td>
      <td><%= link_to "Delete", "/ideas/#{i.id}", method: :delete %></td>
    </tr>
  <% end %>
</table>

app/views/ideas/new.html.erb
<%= link_to "<< Categories Index", admin_categories_path %>
<%= form_for(:idea, url: '/ideas') do |f| %>
  <%= f.label :idea %>
  <%= f.text_field :idea %><br/>

  <%= f.label :category %>
  <%= f.collection_select :category_id, @categories, :id, :category %>

  <%= f.submit "Submit Idea" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IdeaBox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1>Welcome to Idea-Box!</h1>
<% if session[:user_id] != nil %>
  <h4>Welcome, <%= current_user.username %>!</h4>
  <%= link_to "Create Idea >>", new_idea_path %>
<% end %>
<%= yield %>

</body>
</html>

app/views/user/categories/index.html.erb
<%= link_to "Logout", logout_path, method: :delete %>
<%= link_to "Idea Index", ideas_path %>

<h1>Available Categories</h1>

<table class="categories">
  <tr>
    <th>Category Name</th>
  </tr>

  <% @categories.each do |c| %>
    <tr>
      <td><%= c.category %></td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<p>
  <% flash.each do |key, message| %>
    <%= content_tag :div, message, class: "flash_#{key}" %>
  <% end %>
</p>
<%= link_to "<<Homepage", root_path %>
<%= form_for(@user) do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %><br/>

  <%= f.label :password %><br/>
  <%= f.password_field :password %><br/>

  <%= f.submit "Create Account" %>
<% end %>